# Generated by Django 4.2.1 on 2023-08-27 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание актива')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'актив',
                'verbose_name_plural': 'активы',
                'ordering': ('-pub_date',),
                'default_related_name': 'assets',
            },
        ),
        migrations.CreateModel(
            name='AssetInWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TD', 'To Do'), ('IP', 'In progress'), ('CO', 'Complete')], default='TD', max_length=2)),
                ('begin_work', models.DateTimeField(blank=True, verbose_name='начало работы')),
                ('end_work', models.DateTimeField(blank=True, verbose_name='конец работы')),
                ('report', models.TextField(blank=True, verbose_name='отчёт')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset', verbose_name='актив')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='работник')),
            ],
            options={
                'verbose_name': 'актив в работе',
                'verbose_name_plural': 'активы в работе',
            },
        ),
    ]
