# Generated by Django 4.2.1 on 2023-08-28 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetinwork_begin_work_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetinwork',
            old_name='begin_work',
            new_name='begin_date',
        ),
        migrations.RenameField(
            model_name='assetinwork',
            old_name='end_work',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='assetinwork',
            name='todo_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата размещения задания'),
            preserve_default=False,
        ),
    ]
